trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Insperity AzureCloud'
    scriptType: 'ps'
    scriptLocation: 'scriptPath'
    scriptPath: '$(System.DefaultWorkingDirectory)/resource-deployment.ps1'
    arguments: '$(nsp-esc-dev-sqlserver-name), $(nsp-esc-dev-sqlserver-username), $(nsp-esc-dev-sqlserver-pw), "microservice", "centralus", $(nsp-esc-dev-servicebus-name), "payroll"'
    addSpnToEnvironment: true