version: "3.4"
services:
    microservice.two.app:
        image: microservicetwo
        build:
            context: .
            dockerfile: MicroserviceTwo-Dockerfile.Dockerfile
        environment:
            PayrollConnectionString: ${DB_CONNECTIONSTRING?err}
            AppSettings.ServiceBusEndpoint: ${SB_CONNECTIONSTRING?err}
            AppSettings.SubscriberName: "payroll_subscriber"
            AppSettings.PayrollQueueName: "payroll_queue"