// <auto-generated />
using Microservice.One.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Microservice.One.Data.Migrations
{
    [DbContext(typeof(BenefitContext))]
    [Migration("20191216185813_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microservice.One.Data.Model.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "JHL Enterprises"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HCSS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hello Fresh"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Walmart"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Transafe"
                        });
                });

            modelBuilder.Entity("Microservice.One.Data.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ssn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 5,
                            FirstName = "Steve",
                            LastName = "Smith",
                            Ssn = "373637363",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            FirstName = "John",
                            LastName = "Kesinger",
                            Ssn = "123333232",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            FirstName = "James",
                            LastName = "Doe",
                            Ssn = "878676767",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 1,
                            FirstName = "Amanda",
                            LastName = "Know",
                            Ssn = "989887878",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Microservice.One.Data.Model.Hsa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ContributionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hsa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 0m,
                            ContributionAmount = 20m,
                            EmployeeId = 4
                        },
                        new
                        {
                            Id = 2,
                            Balance = 0m,
                            ContributionAmount = 40m,
                            EmployeeId = 2
                        });
                });

            modelBuilder.Entity("Microservice.One.Data.Model.Employee", b =>
                {
                    b.HasOne("Microservice.One.Data.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
